/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Constructors.Customer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    private List<Customer> customers;
    private DefaultTableModel tbl;
    public CustomerForm() {
        initComponents();
        this.setTitle("Customer");
        this.setLocationRelativeTo(null);
        ResetTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String getID(){
        return c_id_txt.getText();
    }
    public String getName(){
        return fname_txt.getText()+" "+lname_txt.getText();
    }
    public void ResetTable(){
        customers = new ArrayList<>();
        tbl = (DefaultTableModel)jTable1.getModel();
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        
        try{
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=ClothingMgmtSvr;user=sa;password=sa");
            String sql = "Select * from customer";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            Vector data = null;
            tbl.setRowCount(0);
            if(rs.isBeforeFirst()==false){
                
                return;
            }
            while(rs.next()){
                data = new Vector();
                data.add(rs.getString("c#"));
                data.add(rs.getString("firstname"));
                data.add(rs.getString("lastname"));
                data.add(rs.getString("gender"));
                data.add(rs.getString("ssn"));
                data.add(rs.getDate("dob"));
                data.add(rs.getString("adress"));
                data.add(rs.getString("phone"));
                data.add(rs.getString("c_rank"));
                tbl.addRow(data);
            }
            jTable1.setModel(tbl);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something is wrong!");
            
        }
    }
    
    private String RandomNumbers(){
        String numberstring = new String();
        Random t = new Random();
        int number = t.nextInt(1000);
        return numberstring = String.format("%03d", number);
    }
    
    public String getCustomerID(){
        return c_id_txt.getText();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Employee = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jSearchNameTxtField = new javax.swing.JTextField();
        SearchByNameButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        c_id_txt = new javax.swing.JTextField();
        fname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        ssn_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        dob_txt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        phone_txt = new javax.swing.JTextField();
        JAddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "S. S. N.", "Date of birth", "Adress", "Phone number", "Rank"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setText("Search by name");

        SearchByNameButton.setText("Search");
        SearchByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByNameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add / Edit customer profile");

        jLabel2.setText("ID");

        jLabel3.setText("First name");

        jLabel4.setText("Last name");

        jLabel5.setText("Social Security no.");

        jLabel6.setText("Address");

        jLabel7.setText("Date of birth");

        jLabel8.setText("Rank");

        jLabel9.setText("Phone number");

        jLabel10.setText("Gender");

        c_id_txt.setEditable(false);

        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Standard");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("VIP");

        JAddButton.setText("Add");
        JAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        HistoryButton.setText("View purchase history");
        HistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Male");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phone_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dob_txt))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(78, 78, 78)
                                .addComponent(address_txt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(ssn_txt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fname_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_id_txt)
                                    .addComponent(lname_txt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HistoryButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(83, 83, 83)
                                        .addComponent(jRadioButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton4))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ssn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAddButton)
                    .addComponent(UpdateButton)
                    .addComponent(RemoveButton)
                    .addComponent(HistoryButton))
                .addContainerGap())
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSearchNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchByNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Employee)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jSearchNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchByNameButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void HistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryButtonActionPerformed
        // TODO add your handling code here:
        History hs = new History(this, true);
        hs.setVisible(true);
    }//GEN-LAST:event_HistoryButtonActionPerformed

    private void SearchByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByNameButtonActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        
        try{
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=ClothingMgmtSvr;user=sa;password=sa");
            String sql = "Select * from customer ";
            if(jSearchNameTxtField.getText().length()>0){
                sql = sql + "where firstname like '%" + jSearchNameTxtField.getText() +"%'";
            }
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            Vector data = null;
            tbl.setRowCount(0);
            if(rs.isBeforeFirst()==false){
                JOptionPane.showMessageDialog(this, "Employee's first name not available!");
                return;
            }
            while(rs.next()){
                data = new Vector();
                data.add(rs.getString("c#"));
                data.add(rs.getString("firstname"));
                data.add(rs.getString("lastname"));
                data.add(rs.getString("gender"));
                data.add(rs.getString("ssn"));
                data.add(rs.getDate("dob"));
                data.add(rs.getString("adress"));
                data.add(rs.getString("phone"));
                data.add(rs.getString("c_rank"));
                tbl.addRow(data);
            }
            jTable1.setModel(tbl);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something is wrong!");
            
        } finally{
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_SearchByNameButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(ret != JOptionPane.YES_OPTION) {
        return;
        }
        int row = jTable1.getSelectedRow();
        String selected = tbl.getValueAt(row, 0).toString();
        Connection c = null;
        PreparedStatement ps = null;
        try {
            c = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=ClothingMgmtSvr;user=sa;password=sa");
            ps = c.prepareStatement("Delete From customer where c# = ?");
            ps.setString(1, selected); //giá trị của cột đầu tiên tại dòng được chọn trong table
            ret = ps.executeUpdate();
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (c != null) {
                c.close();
            }
                if (ps != null) {
                    ps.close();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
        ResetTable();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void JAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddButtonActionPerformed
        Connection c = null;
        Statement st = null;
        ResultSet rs = null;
        String id = new String(c_id_txt.getText());
        String fname = new String(fname_txt.getText());
        String lname = new String(lname_txt.getText());
        String ssn = new String(ssn_txt.getText());
        String address = new String(address_txt.getText());
        String dob = new String(dob_txt.getText());
        String phone = new String(phone_txt.getText());
        String gender = new String();
        if(jRadioButton3.isSelected()) gender = jRadioButton3.getText();
        if(jRadioButton4.isSelected()) gender = jRadioButton4.getText();
        String rank = new String();
        if(jRadioButton1.isSelected()) rank = "Standard";
        if(jRadioButton2.isSelected()) rank = "VIP";
        try{
            c = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=ClothingMgmtSvr;user=sa;password=sa");
            String sql = "insert into customer values ('C"+RandomNumbers()+"', '"+fname+"', '"+lname+"', '"+gender+"', '"+ssn+"', '"+dob+"', '"
                    +address+"', '"+phone+"', '"+rank+"');";
            st = c.createStatement();
            int rows = st.executeUpdate(sql);
            System.out.println("Rows affected: "+rows);
            ResetTable();
//            rs.close();
            st.close();
            c.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something's wrong!");
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_JAddButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        c_id_txt.setText(tbl.getValueAt(row, 0).toString());
        fname_txt.setText(tbl.getValueAt(row, 1).toString());
        lname_txt.setText(tbl.getValueAt(row, 2).toString());
        if(tbl.getValueAt(row, 3).toString().equalsIgnoreCase(jRadioButton3.getText())) jRadioButton3.setSelected(true);
        if(tbl.getValueAt(row, 3).toString().equalsIgnoreCase(jRadioButton4.getText())) jRadioButton4.setSelected(true);
        ssn_txt.setText(tbl.getValueAt(row, 4).toString());
        dob_txt.setText(tbl.getValueAt(row, 5).toString());
        address_txt.setText(tbl.getValueAt(row, 6).toString());
        phone_txt.setText(tbl.getValueAt(row, 7).toString());
        if(tbl.getValueAt(row, 8).toString().equalsIgnoreCase(jRadioButton1.getText())) jRadioButton1.setSelected(true);
        if(tbl.getValueAt(row, 8).toString().equalsIgnoreCase(jRadioButton2.getText())) jRadioButton2.setSelected(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        Connection c = null;
        Statement st = null;
        ResultSet rs = null;
        String id = new String(c_id_txt.getText());
        String fname = new String(fname_txt.getText());
        String lname = new String(lname_txt.getText());
        String ssn = new String(ssn_txt.getText());
        String address = new String(address_txt.getText());
        String dob = new String(dob_txt.getText());
        String phone = new String(phone_txt.getText());
        String gender = new String();
        if(jRadioButton3.isSelected()) gender = jRadioButton3.getText();
        if(jRadioButton4.isSelected()) gender = jRadioButton4.getText();
        String rank = new String();
        if(jRadioButton1.isSelected()) rank = "Standard";
        if(jRadioButton2.isSelected()) rank = "VIP";
        try{
            c = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=ClothingMgmtSvr;user=sa;password=sa");
            String sql = "update customer"
                    + " set firstname = '"+fname+"', lastname = '"+lname+"', ssn = '"+ssn+"', dob = '"+dob+"', adress = '"
                    +address+"', phone = '"+phone+"', c_rank = '"+rank+"', gender = '"+gender+"'"
                    + " where c# = '"+id+"';";
            st = c.createStatement();
            int rows = st.executeUpdate(sql);
            System.out.println("Rows affected: "+rows);
            ResetTable();
//            rs.close();
            st.close();
            c.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Something's wrong!");
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Employee;
    private javax.swing.JButton HistoryButton;
    private javax.swing.JButton JAddButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchByNameButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField address_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c_id_txt;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchNameTxtField;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField ssn_txt;
    // End of variables declaration//GEN-END:variables
}
